In [2]:
import numpy as n

In [3]:
a = [1,2,3]

In [4]:
import numpy as np
np.array(a)

array([1, 2, 3])

In [5]:
print(a)

[1, 2, 3]


In [6]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
print(np.arange(1,11,2).tolist())

[1, 3, 5, 7, 9]


In [9]:
np.linspace(1,100,4)

array([  1.,  34.,  67., 100.])

In [10]:
np.linspace(1,100,4, dtype=np.int8)

array([  1,  34,  67, 100], dtype=int8)

In [11]:
np.zeros((3,3), dtype=np.int8)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones((3,3), dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [14]:
np.empty((4,4), dtype=np.int8)

array([[ 1,  1,  0,  0],
       [ 0,  0,  0,  5],
       [18,  0,  0,  0],
       [11,  0,  0,  0]], dtype=int8)

In [15]:
np.empty((4,4),dtype=np.int8)

array([[101,   0, 112,   0],
       [109,   0,  97,   0],
       [112,   0, 112,   0],
       [101,   0, 114,   0]], dtype=int8)

In [16]:
np.zeros((5,5,5), dtype=np.float16)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float16)

In [17]:
a = np.array([1,2,3])
b= np.array([4,5,6])

print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


In [18]:
np.dot(a,b)

np.int64(32)

In [19]:
print(np.dot(a,b))

32


In [22]:
a = np.array([[1,2,3],
                [4,5,6]])

In [23]:
b = np.array([[8,2,4],
                [4,7,6]])

In [24]:
a*b

array([[ 8,  4, 12],
       [16, 35, 36]])

In [ ]:
np.dot(a,b) # a.shape = 2x3 ; b.shape = 2x3 --> a's number of columns should match with b's number of rows

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [27]:
c = b.T

In [28]:
c

array([[8, 4],
       [2, 7],
       [4, 6]])

In [33]:
d= np.dot(a,c) # 2x3 and 3x2 -->dot --> 2x2
d

array([[24, 36],
       [66, 87]])

In [34]:
print(d)

[[24 36]
 [66 87]]


In [35]:
sum(d)

array([ 90, 123])

In [36]:
print(np.sum(d))

213


In [37]:
e = np.eye(2)

In [38]:
e

array([[1., 0.],
       [0., 1.]])

In [41]:
d*e

array([[24.,  0.],
       [ 0., 87.]])

In [42]:
np.sum(d*e)

np.float64(111.0)

In [43]:

int(np.sum(d*e))

111